    <!-- About Section-->
    <section class="page-section mb-0" id="about">
        <div class="container">
            <!-- About Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase">
                A propos
            </h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- About Section Content-->
            <div class="row">
                <div class="col-lg-4 ms-auto">
                    <p class="lead">
                        Actuellement inscrit chez MyDigitalSchool pour obtenir un titre de
                        Concepteur Développeur d'Applications en un an, je suis
                        profondément motivé à poursuivre mon cursus en vue de ma
                        reconversion professionnelle. Mon objectif ultime est
                        d'approfondir mes compétences et de me spécialiser en tant que
                        développeur full-stack, ambition que je compte concrétiser par la
                        poursuite d'un master dans ce domaine. Je suis conscient que le
                        domaine du développement informatique est en constante évolution,
                        et c'est pourquoi je suis déterminé à rester à la pointe des
                        nouvelles technologies et des meilleures pratiques. Mon ambition
                        est de devenir un expert capable de concevoir et de développer des
                        solutions innovantes et performantes, en m'appuyant sur une solide
                        base de compétences techniques et une vision stratégique.
                    </p>
                </div>
                <div class="col-lg-4 me-auto">
                    <p class="lead">
                        Au cours de ma formation, j'ai développé des compétences solides
                        en programmation, en conception d'interfaces utilisateur, et en
                        résolution de problèmes complexes. Ces compétences, combinées à ma
                        passion pour le développement informatique, me permettent de
                        contribuer de manière significative à des projets innovants. Je
                        suis convaincu que l'alternance représente une opportunité
                        exceptionnelle pour mettre en pratique mes connaissances tout en
                        continuant à les développer. Mon engagement, ma rigueur et ma
                        volonté d'apprendre rapidement font de moi un candidat déterminé à
                        contribuer activement à tous projets.
                    </p>
                </div>
                <div class="col-lg-4 me-auto">
                    <p class="lead">
                        <img src="assets/img/Fabrice_MORY_4.jpg" alt="MoryFabrice" class="img-thumbnail">
                    </p>
                </div>
            </div>
            <!-- About Section Button-->
            <div class="text-center mt-4">
                <a class="btn btn-xl btn-outline-light bg-primary" href="https://moryfabrice.alwaysdata.net/public/download/Cv_Mory_Fabrice.pdf" download>
                    <i class="fas fa-download me-2"></i>
                    Telecharger mon CV !
                </a>
            </div>
        </div>
    </section>