    <!-- Contact Section-->
    <section class="page-section bg-primary text-white" id="contact">
        <div class="container">
            <!-- Contact Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-white mb-0">
                Me Contacter
            </h2>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Contact Section Form-->
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    <form id="contactForm" method="POST" action="index.php/?action=contact">

                        <!-- Name input-->
                        <div class=" form-floating mb-3">
                            <input class="form-control bg-primary text-white" name="nom" type="text" placeholder="Entrer votre nom et prénom..." data-sb-validations="required" />
                            <label class="text-white" for="nom">Nom et Prénom</label>
                            <div class="invalid-feedback" data-sb-feedback="nom:required">
                                Le nom et le prénom sont requis !
                            </div>
                        </div>
                        <!-- Email address input-->
                        <div class="form-floating mb-3">
                            <input class="form-control bg-primary text-white" name="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                            <label class="text-white" for="email">Adresse E-mail</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">
                                Un E-mail est requis !
                            </div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">
                                L'E-mail n'est pas valide
                            </div>
                        </div>
                        <!-- Phone number input-->
                        <div class="form-floating mb-3">
                            <input class="form-control bg-primary text-white" name="telephone" type="tel" placeholder="0601020304" data-sb-validations="required" />
                            <label class="text-white" for="telephone">Numéro de télèphone</label>
                            <div class="invalid-feedback" data-sb-feedback="telephone:required">
                                Un numéro de télèphone est requis.
                            </div>
                        </div>
                        <!-- Message input-->
                        <div class="form-floating mb-3">
                            <textarea class="form-control bg-primary text-white" name="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                            <label class="text-white" for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">
                                Un message est requis.
                            </div>
                        </div>
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <?php if ($retour) { ?>
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                            </div>
                        <?php } ?>
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                            </div>
                        </div>
                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <?php if ($retour != "") { ?>
                            <div class="text-center text-danger mb-3">
                                Error sending message!
                            </div>

                        <?php } ?>
                        <!-- Submit Button-->
                        <button class="btn btn-light btn-xl" name="entrer" type="submit">
                            Envoyer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>