    <!-- Footer-->
    <footer class="footer bg-secondary text-white text-center">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Localité</h4>
                    <p class="lead mb-0">
                        28 rue Arnaud Beltrame
                        <br />
                        59310 Coutiches
                    </p>
                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Où me trouver</h4>
                    <!--  <a class="btn btn-outline-light btn-social mx-1" href="#!"
              ><i class="fab fa-fw fa-facebook-f"></i
            ></a> 
            <a class="btn btn-outline-light btn-social mx-1" href="mory.fabrice@gmail.com"
              ><i class="fas fa-at"></i
            ></a> -->
                    <a class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com/in/fabrice-mory/"><i class="fab fa-fw fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="https://github.com/MoryFabrice"><i class="fab fa-fw fa-github"></i></a>
                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">A propos de moi</h4>
                    <p class="lead mb-0 text-justify">
                        <!-- Jeune développeur recherche alternance mortelle,
                        Une alternance qui pourrait lui donner des ailes,
                        Une entreprise fidèle et qui n'a pas peur qu'on l'aime,
                        Donc si tu as les critères, laisse-moi un email ! -->

                        Jeune développeur recherchant une entreprise afin de
                        pouvoir obtenir le bachelor 3 - Concepteur Développeur
                        D'Applications
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Copyright Section-->
    <div class="copyright py-4 text-center text-white">
        <div class="container">
            <small>MORY Fabrice</small>
        </div>
    </div>