    <!-- Skills Section-->
    <section class="page-section bg-primary text-white mb-0 skills" id="skills">
        <div class="container">
            <!-- skills Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-white mb-0">
                Skills
            </h2>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- skills trie -->
            <div class="mb-4">
                <h3 class="text-center text-uppercase text-white mb-4">Trier par :</h3>
                <div class="text-center">
                    <button class="btn btn-xl btn-outline-light bg-primary text-white m-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFrontEnd" aria-expanded="true" aria-controls="collapseFrontEnd">
                        Front-End
                    </button>
                    <button class="btn btn-xl btn-outline-light bg-primary text-white m-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseBackEnd" aria-expanded="false" aria-controls="collapseBackEnd">
                        Back-End
                    </button>
                    <button class="btn btn-xl btn-outline-light bg-primary text-white m-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFramework" aria-expanded="false" aria-controls="collapseFramework">
                        Framework
                    </button>
                    <button class="btn btn-xl btn-outline-light bg-primary text-white m-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAutres" aria-expanded="false" aria-controls="collapseAutres">
                        Autres
                    </button>
                </div>


            </div>

            <!-- skills Grid Items-->
            <div class="accordion" id="skillsAccordion">

                <div class="">
                    <div class="collapse accordion-collapse show" id="collapseFrontEnd" data-bs-parent="#skillsAccordion">
                        <div class="row justify-content-center">
                            <h1>Html/Css</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="95" aria-valuemax="100"></div>
                            </div>
                            <h1>Javascript</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                            <h1>ReactJS</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                        </div>

                    </div>
                    <div class="collapse accordion-collapse" id="collapseBackEnd" data-bs-parent="#skillsAccordion">
                        <div class="row justify-content-center">
                            <h1>PHP</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="85" aria-valuemax="100"></div>
                            </div>
                            <h1>MySQL</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="85" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse accordion-collapse" id="collapseFramework" data-bs-parent="#skillsAccordion">
                        <div class="row justify-content-center">
                            <h1>Symfony</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="95" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse accordion-collapse" id="collapseAutres" data-bs-parent="#skillsAccordion">
                        <div class="row justify-content-center">
                            <h1>Suite office</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="95" aria-valuemax="100"></div>
                            </div>
                            <h1>Github</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                            <h1>Communication</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                            <h1>Esprit d'équipe</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                            <h1>Analytque</h1>
                            <div class="progress">
                                <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <!-- <div class="collapse" id="collapseFrontEnd" data-bs-parent="#skillsAccordion">
                <div class="">
                    <h1>Html/Css</h1>
                    <div class="progress">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="95" aria-valuemax="100"></div>
                    </div>
                    <h1>Javascript</h1>
                    <div class="progress">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="75" aria-valuemax="100"></div>
                    </div>
                </div>
            </div> -->
    </section>